### ISSUE TITLE
Doesn't work for certain games

### ISSUE THREAD

**Issue by Kamaad1** [IchinichiQ/SteamOverlay#1]
No option to add overlay on any Battle.net, Epic or Origin games, as well as UWP apps. Certain steam games as well, though for obvious reasons this is a non-issue. Is this a known problem?

**Comment by IchinichiQ** [comment]
Currently the extension does not support games from launchers, but the lack of a menu item is indeed a bug. So I'm reopening the issue.
Thanks for the bug report

**Comment by IchinichiQ** [comment]
You can download a new version that includes a fix for this bug from the [releases page](https://github.com/IchinichiQ/SteamOverlay/releases/tag/v0.2)
